title: TrampleTek Blue (HA version)
description: Documentation for the TrampleTek Blue (Home Assistant version).
theme: just-the-docs

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

url: https://ascmats.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
