title: TrampleTek Blue (HA version)
description: Documentation for the TrampleTek Blue (Home Assistant version).
theme: just-the-docs

permalink: pretty

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

url: https://ascmats.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
